
// GENERATED BY Lovable AI

export interface Vehicle {
  id: string;
  title: string;
  type: 'car' | 'bike';
  price: number;
  year: number;
  fuel: 'Petrol' | 'Diesel' | 'Electric' | 'CNG';
  transmission: 'Manual' | 'Automatic';
  image: string;
  location: string;
  mileage?: number;
  brand?: string;
  model?: string;
  featured?: boolean;
  description?: string;
  phone?: string;
  email?: string;
}

export interface Accessory {
  id: string;
  title: string;
  price: number;
  category: 'Interior' | 'Exterior' | 'Electronics' | 'Maintenance' | 'Safety';
  image: string;
  rating: number;
  description?: string;
  brand?: string;
  inStock?: boolean;
}

export interface ContactForm {
  name: string;
  email: string;
  phone: string;
  message: string;
  subject?: string;
}

export interface User {
  id: string;
  email: string;
  name?: string;
  phone?: string;
  created_at: string;
}
