
// GENERATED BY Lovable AI

export interface Vehicle {
  id: string;
  title: string;
  type: 'car' | 'bike';
  price: number;
  year: number;
  fuel: 'Petrol' | 'Diesel' | 'Electric' | 'CNG';
  transmission: 'Manual' | 'Automatic';
  image: string;
  location: string;
  mileage?: number;
  brand?: string;
  model?: string;
  featured?: boolean;
  description?: string;
  phone?: string;
  email?: string;
}

export interface Accessory {
  id: string;
  title: string;
  price: number;
  category: 'Interior' | 'Exterior' | 'Electronics' | 'Maintenance' | 'Safety';
  image: string;
  rating: number;
  description?: string;
  brand?: string;
  inStock?: boolean;
}

export interface ContactForm {
  name: string;
  email: string;
  phone: string;
  message: string;
  subject?: string;
}

export interface User {
  id: string;
  email: string;
  name?: string;
  phone?: string;
  created_at: string;
}

// Database types for products
export interface Product {
  id: number;
  name: string;
  slug: string;
  description?: string;
  price: number;
  price_inr?: number;
  image_url?: string;
  images?: string[];
  category?: string;
  type?: string;
  brand?: string;
  model?: string;
  year?: number;
  fuel?: string;
  transmission?: string;
  location?: string;
  mileage?: number;
  featured?: boolean;
  available: boolean;
  in_stock?: boolean;
  stock: number;
  delivery_days?: number;
  specs?: any;
  created_at?: string;
  updated_at?: string;
}

// Cart types
export interface CartItem {
  id: string;
  user_id: string;
  product_id: number;
  quantity: number;
  created_at: string;
  updated_at: string;
  product?: Product;
}

// Wishlist types
export interface WishlistItem {
  id: string;
  user_id: string;
  product_id?: number | null;
  item_uuid?: string | null; // Added for vehicles/accessories
  item_type?: 'product' | 'vehicle' | 'accessory' | null; // Extended
  created_at: string;
  product?: Product;
}

// User Profile types
export interface UserProfile {
  id: string;
  full_name?: string;
  phone?: string;
  address_line1?: string;
  address_line2?: string;
  city?: string;
  state?: string;
  pincode?: string;
  created_at: string;
  updated_at: string;
}

// Order types
export interface Order {
  id: string;
  user_id?: string;
  product_id: number;
  full_name: string;
  email: string;
  phone: string;
  delivery_address: string;
  delivery_address_line2?: string;
  pincode: string;
  city?: string;
  state?: string;
  total_amount: number;
  quantity?: number;
  item_type?: 'car' | 'bike' | 'accessory';
  payment_id?: string;
  order_notes?: string;
  status: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
  payment_status: 'pending' | 'completed' | 'failed';
  created_at: string;
  updated_at: string;
}
