
import { useState } from 'react';
import { MapPin, Phone, Mail, Clock } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ContactForm from '@/components/ContactForm';

// GENERATED BY Lovable AI
const Contact = () => {
  const contactInfo = [
    {
      icon: MapPin,
      title: 'Visit Us',
      details: ['123 Vehicle Street', 'Connaught Place', 'New Delhi - 110001']
    },
    {
      icon: Phone,
      title: 'Call Us',
      details: ['+91 9999999999', '+91 8888888888', 'Toll Free: 1800-123-4567']
    },
    {
      icon: Mail,
      title: 'Email Us',
      details: ['info@vehiclehub.com', 'support@vehiclehub.com', 'sales@vehiclehub.com']
    },
    {
      icon: Clock,
      title: 'Working Hours',
      details: ['Monday - Saturday: 9:00 AM - 8:00 PM', 'Sunday: 10:00 AM - 6:00 PM', 'Closed on National Holidays']
    }
  ];

  const offices = [
    {
      city: 'Delhi',
      address: '123 Vehicle Street, Connaught Place, New Delhi - 110001',
      phone: '+91 9999999999',
      email: 'delhi@vehiclehub.com'
    },
    {
      city: 'Mumbai',
      address: '456 Auto Lane, Bandra West, Mumbai - 400050',
      phone: '+91 8888888888',
      email: 'mumbai@vehiclehub.com'
    },
    {
      city: 'Bangalore',
      address: '789 Tech Park, Koramangala, Bangalore - 560095',
      phone: '+91 7777777777',
      email: 'bangalore@vehiclehub.com'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      <Navbar />
      
      <div className="pt-24 pb-12">
        {/* Hero Section */}
        <section className="py-16">
          <div className="container mx-auto px-4 text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              Get in <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">Touch</span>
            </h1>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.
            </p>
          </div>
        </section>

        {/* Contact Info Cards */}
        <section className="py-16">
          <div className="container mx-auto px-4">
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
              {contactInfo.map((info, index) => (
                <Card key={index} className="text-center hover:shadow-lg transition-shadow border-0 shadow-md">
                  <CardContent className="p-6">
                    <div className="w-16 h-16 bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
                      <info.icon className="w-8 h-8 text-white" />
                    </div>
                    <h3 className="text-lg font-bold text-gray-900 mb-3">{info.title}</h3>
                    {info.details.map((detail, i) => (
                      <p key={i} className="text-gray-600 text-sm mb-1">{detail}</p>
                    ))}
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* Contact Form Section */}
        <section className="py-16">
          <div className="container mx-auto px-4">
            <div className="grid lg:grid-cols-2 gap-12">
              {/* Contact Form */}
              <div>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Send us a Message</h2>
                <ContactForm />
              </div>

              {/* Office Locations */}
              <div>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Our Offices</h2>
                <div className="space-y-6">
                  {offices.map((office, index) => (
                    <Card key={index} className="border-0 shadow-md">
                      <CardHeader>
                        <CardTitle className="text-xl text-blue-600">{office.city}</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="space-y-3">
                          <div className="flex items-start gap-3">
                            <MapPin className="w-5 h-5 text-gray-400 mt-0.5" />
                            <p className="text-gray-600">{office.address}</p>
                          </div>
                          <div className="flex items-center gap-3">
                            <Phone className="w-5 h-5 text-gray-400" />
                            <p className="text-gray-600">{office.phone}</p>
                          </div>
                          <div className="flex items-center gap-3">
                            <Mail className="w-5 h-5 text-gray-400" />
                            <p className="text-gray-600">{office.email}</p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="py-16 bg-white/50">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-gray-900 mb-12 text-center">Frequently Asked Questions</h2>
            <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-3">How do I list my vehicle?</h3>
                <p className="text-gray-600 mb-6">
                  Simply create an account, click on "Sell Vehicle", and follow our easy step-by-step process to list your vehicle with photos and details.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-3">Are all vehicles verified?</h3>
                <p className="text-gray-600 mb-6">
                  Yes, we have a strict verification process for all vehicles and dealers on our platform to ensure authenticity and quality.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-3">What payment methods do you accept?</h3>
                <p className="text-gray-600 mb-6">
                  We facilitate various payment methods including bank transfers, financing options, and cash payments through our secure platform.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-3">Do you provide warranty?</h3>
                <p className="text-gray-600 mb-6">
                  Many of our certified dealers offer warranty options. Check individual listings for warranty details and coverage.
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>

      <Footer />
    </div>
  );
};

export default Contact;
